# Generated by Django 2.2 on 2022-06-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkstats',
            options={'ordering': ['user', 'park', 'holeNumber', 'holeSub', 'basket', 'tee']},
        ),
        migrations.RemoveField(
            model_name='parkstats',
            name='par',
        ),
    ]
