# Generated by Django 2.2 on 2022-06-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220603_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkstats',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='parkstats',
            name='timesPlayed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
