# Generated by Django 2.2 on 2022-05-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoleCreater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkName', models.CharField(max_length=140)),
                ('holeNumber', models.IntegerField()),
                ('holeSub', models.CharField(blank=True, max_length=1, null=True)),
                ('par', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
