# Generated by Django 2.2 on 2022-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holecreater',
            name='tee',
            field=models.CharField(default='Red', max_length=10),
        ),
    ]
