# Generated by Django 2.2 on 2022-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_holecreater_tee'),
    ]

    operations = [
        migrations.AddField(
            model_name='holecreater',
            name='basket',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
