# Generated by Django 2.2 on 2022-05-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220518_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=140, unique=True)),
                ('num_holes', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='holecreater',
            name='parkName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCreator'),
        ),
    ]
