# Generated by Django 2.2 on 2022-05-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20220521_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseCreator',
            new_name='ParkCreator',
        ),
    ]
