# Generated by Django 2.2 on 2022-05-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220521_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holecreater',
            name='basket',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='holecreater',
            name='holeSub',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='holecreater',
            name='tee',
            field=models.CharField(default='White', max_length=10),
        ),
    ]
