# Generated by Django 2.2 on 2022-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220522_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkcreator',
            name='park_name',
            field=models.CharField(max_length=140),
        ),
    ]
