# Generated by Django 2.2 on 2022-05-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220522_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holecreater',
            name='parkName',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='parkcreator',
            name='park_name',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
