# Generated by Django 2.2 on 2022-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220522_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holecreater',
            name='basket',
            field=models.CharField(default='z', max_length=10),
        ),
        migrations.AlterField(
            model_name='holecreater',
            name='holeSub',
            field=models.CharField(default='z', max_length=1),
        ),
    ]
