# Generated by Django 2.2 on 2022-06-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20220607_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holecreater',
            options={'ordering': ['parkName', 'holeNumber', 'holeSub', 'basket']},
        ),
        migrations.AlterField(
            model_name='holecreater',
            name='basket',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='holecreater',
            name='holeSub',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
