# Generated by Django 3.2 on 2024-07-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220615_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holecreater',
            name='basket',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='holecreater',
            name='holeSub',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
