# Generated by Django 2.2 on 2022-06-01 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play_game', '0002_currentgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecreator',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
