# Generated by Django 2.2 on 2022-06-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_game', '0007_auto_20220601_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgame',
            name='progress',
            field=models.CharField(default='done', max_length=140),
        ),
    ]
