# Generated by Django 2.2 on 2022-06-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play_game', '0008_auto_20220601_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=140)),
                ('park', models.CharField(max_length=140)),
                ('hole', models.IntegerField()),
                ('holeNumber', models.IntegerField()),
                ('holeSub', models.CharField(blank=True, max_length=1)),
                ('basket', models.CharField(blank=True, max_length=10)),
                ('tee', models.CharField(max_length=10)),
                ('distance', models.IntegerField()),
                ('throws', models.IntegerField()),
                ('par', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
