# Generated by Django 2.2 on 2022-06-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_game', '0011_gamecreator_park'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesave',
            options={'ordering': ['card', 'hole', 'holeSub', '-timestamp']},
        ),
    ]
