# Generated by Django 2.2 on 2022-06-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_game', '0012_auto_20220608_1326'),
        ('play_game', '0012_auto_20220608_1544'),
    ]

    operations = [
    ]
