# Generated by Django 2.2 on 2022-06-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_game', '0013_merge_20220608_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecreator',
            options={'ordering': ['game', 'hole', 'holeSub', '-timestamp']},
        ),
    ]
