# Generated by Django 2.2 on 2022-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCardCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=140)),
                ('parkName', models.CharField(max_length=140)),
                ('numOfHoles', models.IntegerField()),
            ],
        ),
    ]
