# Generated by Django 2.2 on 2022-05-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCardHoleCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=140, unique=True)),
                ('holeNumber', models.IntegerField()),
                ('holeSub', models.CharField(blank=True, max_length=1)),
                ('basket', models.CharField(blank=True, max_length=10)),
                ('tee', models.CharField(max_length=10)),
                ('distance', models.IntegerField()),
                ('par', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='scorecardcreator',
            name='cardName',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
