# Generated by Django 2.2 on 2022-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0002_auto_20220526_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecardholecreator',
            name='card_name',
            field=models.CharField(max_length=140),
        ),
    ]
