# Generated by Django 2.2 on 2022-06-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0003_auto_20220526_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecardholecreator',
            options={'ordering': ['card_name', 'holeNumber', 'holeSub']},
        ),
    ]
