# Generated by Django 2.2 on 2022-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0004_auto_20220603_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardholecreator',
            name='park_name',
            field=models.CharField(default='park', max_length=140),
            preserve_default=False,
        ),
    ]
