# Generated by Django 2.2 on 2022-06-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0005_scorecardholecreator_park_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecardholecreator',
            options={'ordering': ['card_name', 'hole', 'holeNumber', 'holeSub']},
        ),
        migrations.AddField(
            model_name='scorecardholecreator',
            name='hole',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
